### ISSUE TITLE
Problem with Leanplum's variables after identifying.

### ISSUE THREAD

**Issue by paulsbin** [Leanplum/Leanplum-Segment-iOS#7]
Hello,

I think you have a problem with method: [- (void)identify:(SEGIdentifyPayload *)payload](https://github.com/Leanplum/Leanplum-Segment-iOS/blob/0cdb103753c3721f8d6b244afbb037f60dd49d2f/Pod/Classes/SEGLeanplumIntegration.m#L56).
After setting userId, you should call [Leanplum forceContentUpdate]. It's necessary to get actual variables for specific userId. Also I can't manually call [Leanplum forceContentUpdate] after identifying, because your implementation is asynchronous.

Please, pay attention about this problem in other mobile platforms.

Best regards.

**Comment by nzagorchev** [comment]
The `setUserId` method does not have a callback and is not send immediately. You can call `[Leanplum forceContentUpdate] `after `identify` request.
